// front-end/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
import { ref } from 'vue';

</script>

<template>
  <h1>Simple Editor</h1>
  <nav>
    <RouterLink to="/">Home</RouterLink>
    <RouterLink to="/about">About</RouterLink>
    <RouterLink to="/notfound">404</RouterLink>
  </nav>
  <RouterView/>
  <!--<div id="app">
    <SimpleEditor></SimpleEditor>
  </div>-->
</template>

// front-end/src/App.tsx
import './App.css'
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import NotFound from './pages/NotFound'
import Layout from './pages/Layout'
import Home from './pages/Home'
import Simple from './pages/Editor'


function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path='/' element={<Layout/>}>
          <Route index path='/' element={<Home/>}/>
          <Route path='/editor' element={<Simple/>}/>
          <Route path='*' element={<NotFound/>}/>
        </Route>
      </Routes>
    </BrowserRouter>
  )
}

export default App
